<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Payment Detail <?php echo $site_name; ?>!</title>
</head>

<body style="padding:0; margin:0;">
<table width="700" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #f5821f; padding:0 15px;">
  
  <tr>
    <td align="left"><a href="<?php echo base_url(); ?>" target="_blank"><img src="<?php echo base_url().$this->config->item('email_logo'); ?>" alt="FICCI Logo" style="display:block; border:0;" /></a></td>
  </tr>
  
  
  <tr>
  <td>
  <h4 style="font:bold 20px Arial, Helvetica, sans-serif; color:#000; text-align:center">Payment Detail  <?php echo $site_name; ?></h4>
  </td>
  </tr>
  
  <tr>
    <td align="left" style="font:normal 13px Arial, Helvetica, sans-serif; color:#000;"><p>Dear <?php echo trim($name) ?>, <br />
      <br />
Thank you for providing your payment details for the <b>FICCI Online Certificate Course on (<?php echo $site_name; ?>), Session- <?php echo $sessionStartMonth; ?> - <?php echo $sessionEndMonth; ?> <?php echo $sessionYear; ?>. </b><br />
<br />
Your cheque/demand draft details are provided below for future reference and record.<br />
<br />
Same details filled in the form: <br />
<br />
<b>Payment Mode: <?php echo $payment_type; ?></b><br/>
<b>Reference No:<?php echo $reference_no; ?></b><br/>
<b>Date:<?php echo $payment_date; ?></b><br/>
<b>Amount:<?php echo $course_fee; ?></b><br/>
<b>Bank Name:<?php echo $bank_name; ?></b><br/>
<b>Branch:<?php echo $branch_name; ?></b><br/>

Once your cheque/DD gets cleared from bank, an Account Activation Mail stating your Enrolment Number will be generated by FICCI. 
<br/>
Online Access to the Course will only be available from the date of commencement of the course, as notified by FICCI.
<br/>
Should you require any clarification or further information, please feel free to contact the undersigned.
<br /><br />





With best regards,<br />
<strong>Course Coordinator</strong><br />
FICCI-IP Education Centre (IPEC)<br/>
<strong>Federation of Indian Chambers of Commerce and Industry</strong> <br />
</p></td>
  </tr>

  <tr>
    <td align="center"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td colspan="2" style="font:normal 14px Arial, Helvetica, sans-serif; color:#000;">
           FICCI | Industry's Voice For Policy Change<br />

			Contact No: 18003136160 (Toll free ) +91-11- 23487477 <br />
			E: <a href="mailto:ipcourse@ficci.com" target="_blank" style="outline:none; color:#000;">ipcourse@ficci.com</a>  | <a href="www.ficciipcourse.in" target="_blank" style="outline:none; color:#000;">W: www.ficciipcourse.in</a> <br />

          </td>
          
        </tr>
      </table></td>
  </tr>
  
</table>
</body>
</html>