<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome to <?php echo $site_name; ?>!</title>
</head>

<body style="padding:0; margin:0;">
<table width="700" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #f5821f; padding:0 15px;">

  <tr>
    <td align="left"><a href="<?php echo base_url(); ?>" target="_blank"><img src="<?php echo base_url().$this->config->item('email_logo'); ?>" alt="FICCI Logo" style="display:block; border:0;" /></a></td>
  </tr>
   
  <tr>
  <td>
  <h4 style="font:bold 20px Arial, Helvetica, sans-serif; color:#000; text-align:center">Welcome to <?php echo $site_name; ?></h4>
  </td>
  </tr>
  
  <tr>
    <td align="left" style="font:normal 13px Arial, Helvetica, sans-serif; color:#000;">
	<p>Dear <?php echo $name ?> , <br />
      <br />
	Greetings from Federation of Indian Chambers of Commerce & Industry (FICCI)!<br/><br/>

	We wish to inform you that your Account Activation formalities for the <strong>FICCI Online Certificate Course on Intellectual Property(IP), Session- <?php echo $sessionStartMonth ?> to <?php echo $sessionEndMonth ?> <?php echo $sessionYear ?> </strong>are still pending. <br/><br/>

<strong>For successful registration kindly refer to the  following Account Activation Instructions: </strong><br />

<ul>
<li>Payment for the Course, as applicable to students and participants from the Industry, is to be made only through Cheque or Demand Draft in favour of “FICCI”, payable at New Delhi (online payment option NOT available)</li>
<li>The Registrants are requested to write the Name, User ID made while registering online and Contact Number/Mobile Number, on the reverse side of the Cheque or Demand Draft.</li>

<li>The Cheque or Demand in favour of “FICCI”, is to be sent to FICCI Office through courier/speed post, addressed to Mr. Dipankar Barkakati, Additional Director & Head, IPR Division Federation of Indian Chambers of Commerce and Industry (FICCI), Federation House, Tansen Marg, New Delhi – 110001.</li>

<li>The Cheque/DD should reach to the above mentioned address by the last date, as notified by FICCI. Meanwhile, please click here to fill in your Cheque/Demand Draft details.</li>

<li>Once the payment has been received an Account Activation Mail consisting of Enrollment Number will be generated by FICCI.</li>

<li>Online Access to the Course will only be available from the date of commencement of the course, as notified by FICCI.</li>
</ul>

Should you require any clarification or further information, please feel free to contact the undersigned. <br /><br />


With best regards,<br />
<strong>Course Coordinator</strong><br />
FICCI-IP Education Centre (IPEC)<br/>
<strong>Federation of Indian Chambers of Commerce and Industry</strong> <br />
</p></td>
  </tr>

  <tr>
    <td align="center"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td colspan="2" style="font:normal 14px Arial, Helvetica, sans-serif; color:#000;">
         FICCI | Industry's Voice For Policy Change<br />

			Contact No: 18003136160 (Toll free ) +91-11- 23487477 <br />
			E: <a href="mailto:ipcourse@ficci.com" target="_blank" style="outline:none; color:#000;">ipcourse@ficci.com</a>  | <a href="www.ficciipcourse.in" target="_blank" style="outline:none; color:#000;">W: www.ficciipcourse.in</a> <br />

          </td>
          
        </tr>
      </table></td>
  </tr>
 
</table>
</body>
</html>